### ISSUE TITLE
稳定了吗 是否可用于生产

### ISSUE THREAD

**Issue by jonny77** [kanyxmo/MineAdmin#1]

**Comment by kanyxmo** [comment]
回答大佬的问题：
1.项目是可以用于生产的，只要使用master的代码或者下载最新标签的发行版都没有问题。
2.项目也一直在维护和更新中，保持系统健壮和稳定性。

**Comment by lanshe** [comment]
发现晚了，github刚推荐过来。。目前php管理后台中，貌似只有这一个自带数据权限的。。SCUI这个框架也很棒

**Comment by littlezo** [comment]
已上生产环境，目前无问题
