### ISSUE TITLE
导入功能无效

### ISSUE THREAD

**Issue by cruelwolfking** [kanyxmo/MineAdmin#20]
点击上传或者拖入文件都没有反应

**Comment by kanyxmo** [comment]
你什么浏览器？
chrome 没事
![image](https://user-images.githubusercontent.com/1711988/192800260-dcb0e4a6-5269-4b25-b738-b2b699fcc8f6.png)

edge 也没事
![image](https://user-images.githubusercontent.com/1711988/192800415-4f499cfd-64dc-4de2-a385-726309badb4e.png)

**Comment by cruelwolfking** [comment]
这个已确认浏览器兼容性问题，谷歌部分版本不支持
