### ISSUE TITLE
列表增加了select count(*)  导致查询效率非常低，300万的单表，每次列表要等待8s

### ISSUE THREAD

**Issue by cruelwolfking** [kanyxmo/MineAdmin#21]
感觉这个非常不合理，为什么要查一次select count(*) ，之前都不需要的啊。我说怎么列表卡得要命，切下一页每次都要等7s

**Comment by kanyxmo** [comment]
数字型分页肯定要查数据总量的，你可以用简单型分页，就上一页下一页这种。

**Comment by iwzh** [comment]
> 感觉这个非常不合理，为什么要查一次select count(*) ，之前都不需要的啊。我说怎么列表卡得要命，切下一页每次都要等7s

有主键，300万应该不至于这么久呀

**Comment by NEKGod** [comment]
这个大概率是那个临时表 tmp 太小了
