### ISSUE TITLE
一键curd生成单选框 单选框字段配置项 value值为code 

### ISSUE THREAD

**Issue by NEKGod** [kanyxmo/MineAdmin#24]
一键curd生成单选框 单选框字段配置项 value值为code 与ma-curd组件中的value不一致

建议将`  {
    title: "是否推荐",
    dataIndex: "is_show",
    formType: "radio",
    search: true,
    dict: {
      data: [
        {
          label: "是",
          value: "1"
        },
        {
          label: "否",
          value: "0"
        }
      ],
      translation: true
    }
  },`
改成`  {
    title: "是否推荐",
    dataIndex: "is_show",
    formType: "radio",
    search: true,
    dict: {
      data: function () {
         return [
        {
          label: "是",
          value: "1"
        },
        {
          label: "否",
          value: "0"
        }
      ];
      },
      translation: true
    }
  },`

**Comment by kanyxmo** [comment]
前端已同步修改为value了
