### ISSUE TITLE
模块直接是否可以增加依赖关系呢

### ISSUE THREAD

**Issue by ljyljy0211** [kanyxmo/MineAdmin#42]
建议：
模块之间是否可以增加依赖关系呢？毕竟不是微服务模式，如果开发单体应用，例如会员模块，其他许多模块都会依赖它，这样如果卸载模块，就要看是否有模块依赖了它，不能随意就卸载了，所以可以在config.json中增加依赖模块配置

**Comment by kanyxmo** [comment]
可以，挺好的想法。但目前无法给出一个详细的时间表
