### ISSUE TITLE
API接口极简模式问题

### ISSUE THREAD

**Issue by NonSecurity** [kanyxmo/MineAdmin#6]
App\System\Service\SystemAppService

![image](https://user-images.githubusercontent.com/19179961/164967963-198f82bd-3329-4c4f-be9b-11c8b0948eea.png)
查询里面没有带app_id，而下面使用的是$model->app_id，根本拿不到

**Comment by kanyxmo** [comment]
已经修复了
https://github.com/kanyxmo/MineAdmin/commit/4a7d8862293cf47af5d0c241850398b9b35ed394
