### ISSUE TITLE
能否支持限制账号登陆/手机登录/邮箱登录

### ISSUE THREAD

**Issue by sorshion** [kanyxmo/MineAdmin#70]
在台湾地区，日本等地区，一般使用邮箱进行账号登录，能否增强这块实现

**Comment by kanyxmo** [comment]
系统不会单独实现这个，自己重写登录和退出替换系统的就可以了，很简单的

**Comment by kanyxmo** [comment]
![image](https://github.com/kanyxmo/MineAdmin/assets/1711988/9c4e4f87-4bc7-4fbd-9601-363ec4ed0c85)

**Comment by sorshion** [comment]
thx
